### ISSUE TITLE
Application of clock correction from CLAS or MADOCA

### ISSUE THREAD

**Issue by whu-dyf** [hirokawa/cssrlib-data#32]
According to IS-QZSS-L6-005, the recovery procedure for the broadcast clock should involve subtracting corrections. However, in the cssrlib implementation, the corrections are being added instead. The test results indicate that the code is functioning correctly, which is confusing. Could you please help me understand this discrepancy? Thanks for your reply in advance!
![image](https://github.com/hirokawa/cssrlib-data/assets/31154686/064999ad-4080-446c-b65e-01b0603efd81)
![image](https://github.com/hirokawa/cssrlib-data/assets/31154686/2c3b4f38-14fe-4a72-9e06-e923028d016b)

**Comment by hirokawa** [comment]
dts is substracted from t_broadcast, so the sign is correct.
For the details of the sign convention, please refer to our ION GNSS+ 2023 paper (https://doi.org/10.33012/2023.19207).

**Comment by whu-dyf** [comment]
> dts is substracted from t_broadcast, so the sign is correct. For the details of the sign convention, please refer to our ION GNSS+ 2023 paper (https://doi.org/10.33012/2023.19207).

Your paper clarified my question very clearly, thank you so much!
