### ISSUE TITLE
About  errors 「KeyError: <sCType.CBIAS: 3>」

### ISSUE THREAD

**Issue by niuxiansen2** [hirokawa/cssrlib-data#33]
Dear Dr. hirokawa,

Thank you for providing this excellent code.
However, I have one question about  some errors while running it

````
Traceback` (most recent call last):
  File "/content/cssrlib-data/samples/test_ppprtcm.py", line 192, in <module>
    _, _, eph = cs.decode(msg[k:k+cs.len+3])
  File "/usr/local/lib/python3.10/dist-packages/cssrlib/rtcm.py", line 1651, in decode
    i = self.decode_cssr_cbias(msg, i)
  File "/usr/local/lib/python3.10/dist-packages/cssrlib/rtcm.py", line 526, in decode_cssr_cbias
    if timediff(self.time, self.lc[inet].t0[sCType.CBIAS]) > 0:
KeyError: <sCType.CBIAS: 3>
```
Thank you very much!
Best regards.

**Comment by AndreHauschild** [comment]
I assume you are using the `main` branch? This issue is fixed in the `devel` branch. Please try using this instead.

**Comment by niuxiansen2** [comment]
> I assume you are using the `main` branch? This issue is fixed in the `devel` branch. Please try using this instead.

Thank you so much for your  helpful response ，I use the code from the devel branch, it run successfully.
