### ISSUE TITLE
Can ccsrlib convert the parsed PPP correction (Galileo HAS format or BDS HAS format) to RTCM-SSR?

### ISSUE THREAD

**Issue by whu-dyf** [hirokawa/cssrlib-data#4]
Dear Hirokawa，
First of all, thank you for your work on CSSRLib.
I have a question regarding the library: Can CSSRLib convert parsed PPP corrections (in Galileo HAS or BDS HAS format) to RTCM-SSR? Additionally, I noticed that some classes in the newly added test_ppphas module, such as cssrlib.cssr_has and cssrlib.pppssr, are missing from the CSSRLib library. Could you provide more information on this? Finally, I was wondering what the format of the sample data for Galileo HAS and BDS-PPPB2B is. 
Thank you for your time and contribution to the community.

**Comment by hirokawa** [comment]
Thank you for your comment. Currently, CSSRlib isn't supporting CSSR (or similar) to RTCM-SSR conversion. It is not so difficult, it could be supported in future.
For the newly added class, they are included in new_sig branch of cssrlib. Once the test has been completed, it will be merged into the master branch.
A sample data of Galileo HAS or BDS-PPP is included in cssrlib-data/data (gale6*, bdsb2b*).

**Comment by whu-dyf** [comment]
这是来自本人设置的自动回复您好，您的来信我已收到:)

**Comment by whu-dyf** [comment]
Thank you for your response. To clarify, I was wondering how you obtained the sample data for Galileo HAS and BDS PPP in the format that you provided. Would you be able to share more information on the source of the data? Thank you.

> Thank you for your comment. Currently, CSSRlib isn't supporting CSSR (or similar) to RTCM-SSR conversion. It is not so difficult, it could be supported in future.
> For the newly added class, they are included in new_sig branch of cssrlib. Once the test has been completed, it will be merged into the master branch.
> A sample data of Galileo HAS or BDS-PPP is included in cssrlib-data/data (gale6*, bdsb2b*).

**Comment by hirokawa** [comment]
The data was collected by Javad receiver which can track E6/B2b. I think that Septentrio with the newest firmware can also track E6/B2b.

**Comment by whu-dyf** [comment]
这是来自本人设置的自动回复您好，您的来信我已收到:)
